# Development-specific overrides and additions
# Use with: docker compose -f docker-compose.base.yml -f docker-compose.dev.yml up

services:
  # Development database overrides
  db:
    volumes:
      # Add dev-specific init script
      - ./database/init-dev.sql:/docker-entrypoint-initdb.d/01-init-dev.sql:ro
    ports:
      # Expose database port for direct access
      - "5432:5432"

  # Development API overrides
  api:
    ports:
      # Expose API port for direct access
      - "5000:5000"

  # Development frontend overrides
  frontend:
    ports:
      # Expose frontend port
      - "3000:3000"

  # Development Trivy overrides
  trivy:
    ports:
      # Expose trivy port for direct access
      - "${TRIVY_PORT}:${TRIVY_PORT}"

  # Development-only services
  mock-idp:
    build:
      context: ./mock-idp
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - "8081:8081"
    networks:
      - app-network

  mock-npm-registry:
    build:
      context: ./mock-npm-registry
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - npm_storage:/app/storage
    networks:
      - app-network

volumes:
  # Add dev-specific volumes
  npm_storage: