# Production-specific overrides
# Use with: docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up

services:
  # Production API overrides (if needed)
  api:
    # Production-specific environment overrides can go here
    # For example, different logging levels, etc.
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0

  # Production frontend overrides (if needed)
  frontend:
    # Production-specific frontend overrides can go here
    # For example, different build args, etc.
    environment:
      - NODE_ENV=production

  # Production Trivy overrides (if needed)
  trivy:
    # Production-specific Trivy configuration can go here
    # For example, different cache settings, etc.
    restart: always
